[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."process-scheduled-emails"]
  schedule = "*/30 * * * *"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/bdm"
  to = "/bdm.html"
  status = 200
